export default {
  DatingIconColor: require("../assets/images/DatingIconColor.png"),
  BigLogo: require("../assets/images/BigLogo.png"),
  DearBabyLogo: "https://ade93f25f7.draftbit.media/DearbabyLogo.png",
  ObFB: require("../assets/images/ObFB.png"),
  ObGoogle: require("../assets/images/ObGoogle.png"),
  ObApple: require("../assets/images/ObApple.png"),
  Ellipse21: require("../assets/images/Ellipse21.png"),
  EditPicFrame: require("../assets/images/EditPicFrame.png"),
  VickyHladynetsC8Ta0gwPbQgUnsplash: require("../assets/images/VickyHladynetsC8Ta0gwPbQgUnsplash.jpg"),
  LoginBGImg: require("../assets/images/LoginBGImg.png"),
  FB: require("../assets/images/FB.png"),
  Apple: require("../assets/images/Apple.png"),
  Google: require("../assets/images/Google.png"),
  Filter: require("../assets/images/Filter.png"),
  Group162742: require("../assets/images/Group162742.png"),
  Camera: require("../assets/images/Camera.png"),
  Gallery: require("../assets/images/Gallery.png"),
  File: require("../assets/images/File.png"),
  Location: require("../assets/images/Location.png"),
  Audio: require("../assets/images/Audio.png"),
  Contact: require("../assets/images/Contact.png"),
  Sendmsg: require("../assets/images/Sendmsg.png"),
  Fbicon: require("../assets/images/Fbicon.png"),
  Twitter: require("../assets/images/Twitter.png"),
  Insta: require("../assets/images/Insta.png"),
  SearchPeopleNearby: require("../assets/images/SearchPeopleNearby.png"),
};
