import { systemWeights } from "react-native-typography";
import palettes from "./palettes";
import { createTheme, DefaultTheme } from "@draftbit/ui";
export default createTheme({
  breakpoints: {},
  palettes,
  baseTheme: DefaultTheme,
  theme: {
    name: "Draftbit",
    colors: {
      background: {
        base: palettes.Socialize["Background → #F8FAFC"],
        brand: palettes.Brand.Background,
        danger: palettes.Brand.Error,
      },
      border: {
        base: palettes.Brand.Divider,
        brand: palettes.Brand.Divider,
        danger: palettes.Brand.Error,
      },
      branding: {
        accent: palettes.Socialize.accent3,
        primary: palettes.Socialize["primary #0A84FF"],
        secondary: palettes.Socialize.accent,
        tertiary: palettes.Socialize.accent2,
      },
      foreground: {
        base: palettes.Brand.Light,
        brand: palettes.Brand.Light,
        danger: palettes.Brand.Light,
      },
      text: {
        danger: palettes.Socialize["Danger → #EF4444"],
        light: palettes.Brand.Light,
        medium: palettes.Socialize.mutedText,
        normal: palettes.Socialize.Test,
        strong: palettes.Socialize.Test,
        success: palettes.Socialize["Success → #10B981"],
        warning: palettes.Socialize["Warning → #F59E0B"],
      },
    },
    typography: {
      body1: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 16,
        lineHeight: 26,
        letterSpacing: 0,
        fontFamily: "Inter_400Regular",
      },
      body2: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 14,
        lineHeight: 22,
        letterSpacing: 0,
        fontFamily: "Inter_400Regular",
      },
      button: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 14,
        lineHeight: 16,
        letterSpacing: 0,
        fontFamily: "Inter_400Regular",
      },
      caption: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0,
        fontFamily: "Inter_400Regular",
      },
      headline1: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 60,
        lineHeight: 71,
        letterSpacing: 0,
        fontFamily: "InterTight_400Regular",
      },
      headline2: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 48,
        lineHeight: 58,
        letterSpacing: 0,
        fontFamily: "InterTight_400Regular",
      },
      headline3: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 34,
        lineHeight: 40,
        letterSpacing: 0,
        fontFamily: "InterTight_400Regular",
      },
      headline4: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 24,
        lineHeight: 34,
        letterSpacing: 0,
        fontFamily: "InterTight_400Regular",
      },
      headline5: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 20,
        lineHeight: 26,
        letterSpacing: 0,
        fontFamily: "InterTight_400Regular",
      },
      headline6: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 16,
        lineHeight: 24,
        letterSpacing: 0,
        fontFamily: "InterTight_400Regular",
      },
      overline: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 2,
        fontFamily: "Inter_400Regular",
      },
      subtitle1: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 16,
        lineHeight: 26,
        letterSpacing: 0,
        fontFamily: "Inter_400Regular",
      },
      subtitle2: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: "400",
        fontSize: 14,
        lineHeight: 22,
        letterSpacing: 0,
        fontFamily: "Inter_400Regular",
      },
    },
  },
});
